services:
  mongo:
    image: mongo:8.0-noble
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-config:/data/configdb
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
  mysql:
    image: mysql:8.4-oracle
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
  redis:
    image: redis:8.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --requirepass password

volumes:
  mongo-config:
  mongo-data:
  postgresdata:
  mysqldata:
  redisdata:
