services:
  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:8.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI

volumes:
  postgresdata:
  redisdata:
