services:
  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:8.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --requirepass password

volumes:
  postgresdata:
  redisdata:
