## Namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth

## Postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: auth
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.5-alpine3.22 # "https://hub.docker.com/_/postgres"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: storage
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: auth
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
