## MySQL
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: courses
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4.5-oraclelinux9 # "https://hub.docker.com/_/mysql"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: db
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: storage
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: courses
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306
